version: "3"

services:
  meilisearch:
    image: getmeili/meilisearch:v0.28.0
    environment:
      - MEILI_MASTER_KEY=123changeme
      - MEILI_ENV=development
    ports:
      - 7700:7700
    volumes:
      - ./data.ms:/data.ms
    networks:
      default: ~
